### ISSUE TITLE
configured value used instead of system provided for origin@48577

### ISSUE THREAD

**Issue by kortemik** [teragrep/jla_05#2]
configured value used instead of system provided for origin@48577

https://github.com/teragrep/jla_05/blob/master/src/main/java/com/teragrep/jla_05/RelpAppender.java#L204

this must be changed to use system provided by calling 
```
java.net.InetAddress.getLocalHost().getHostName();
```
at the appender initialization. multiple calls must be avoided to avoid extra calls to DNS.

**Comment by StrongestNumber9** [comment]
Fixed in release 1.1.0
